#!/bin/sh
# Create all types, functions, tables and views in the correct order.

# Usage:
#   sql/create_all | psql <database>

FILES="\
 ../../sql/djet.sql\
 ../../sql/basic.sql\
 ../../sql/user.sql\
 ../../sql/blog.sql\
 ../../sql/contactform.sql\
 ../../sql/roles.sql\
 sql/basic.sql\
"
cat $FILES
