=head1 NAME

Djet::Manual - Index of the Manual

=head1 DESCRIPTION

This is the L<Jet> users manual. Jet is Node based Content Management System (CMS).

The primary features of Jet are

=over

=item *

Jet uses advanced features from the Perl ecosystem, such as L<Plack>/PSGI, L<DBIx::Class>, L<Moose> to do the hard work

=item *

Jet also uses L<PostgreSQL|http://www.postgresql.org>

PostgreSQL provides many advanced features, such as 

=over

=item 1

Full-Text Search

=item 2

Arrays

=item 3

Extensible datatypes (like prefix, that is used for efficient basetype finding)

=item 4

Server-side functions and triggers

=back

=item *

Something

=back

=head1 SECTIONS

=head2 L<Djet::Manual::Startup>

The startup sequence

=cut

