=head1 NAME

Djet::Manual::Startup - Description of the startup "sequence"

=head1 DESCRIPTION

This document describes the way Djet performs a startup.

=head1 Modules

=head2 Djet::Starter

Djet::Starter is instantiated in app.psgi, making it a singleton (at least within the
address space of a single web server process).

Has the following attributes

=over 4

=item params

Searches the environment for parameters starting with JET_ (case insensitive) and hands them over to config.
The JET_ prefix is removed, such that JET_APP_ROOT sets the config parameter app_root.

These parameters make sense to set as environment variables:

=over 4

=item * djet_root

=item * app_root

=item * log_category

=item * log_adapter

=back

=item config

Djet::Starter initializes the configuration.

=item model

The model acts as a model containing all the relevant data for Djet, including the
DBIC database model, the configuration, and a hashref with the basetypes.

=item app

The sub that plack will call. Contains the model, which holds the Djet view of the world,
including the configuration.

=back

=head2 Djet::Config

Contains the 'static' Djet data, including

=over 4

=item djet_root

The path to Djet's home directory.

=item app_root

The path to the application's home directory

=item config

The configuration, fetched from the configuration file(s)a.

=item renderers

A hashref with the renderer objects (HTML, JSON)

=item log (Yet to come)

The logger

=back

=head2 Djet::Model

=over 4

=item config

Set from Djet::Starter, contains the entire configuration.

=item basetypes

A hashref containing the basetypes is kept around for performance reasons.

=item ... the rest

Djet::Schema is also an ordinary DBIC Schema class.

=back

