#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use JSON;

use Data::Dumper;

use Jet::Config;
use Jet::Stuff;

sub basetype_engine {
	my $data = [
		{
			name => 'List',
			conditions => [
				{
					part => 'Compare',
					static => {
						two => undef,
					},
				},
			],
			steps => [
				{
					part => 'Stash',
					static => {
						stashname => 'basetypes',
						request_method    => 'get_basetypes',
						order     => 'id',
					},
				},
			],
		},
		{
			name => 'Create',
			conditions => [
				{
					part => 'Compare',
					static => {
						two => undef,
					},
				},
				{
					part => 'Request::Method',
					static => {
						request_method  => 'POST',
					},
				},
			],
			steps => [
				{
					part => 'Update',
					static => {
						stashname => 'basetype',
						method    => 'update_basetype',
					},
				},
			],
		},
		{
			name => 'Update',
			conditions => [
				{
					part => 'Compare',
					static => {
						two => /^\d+$/,
					},
				},
				{
					part => 'Request::Method',
					static => {
						method  => 'POST',
					},
				},
			],
			steps => [
				{
					part => 'Update',
					static => {
						stashname => 'basetype',
						method    => 'update_basetype',
					},
				},
				{
					part => 'Stash',
					static => {
						stashname => 'basetype',
						method    => 'find_basetype',
					},
				},
			],
		},
		{
			name => 'Retrieve',
			conditions => [
				{
					part => 'Compare',
					static => {
						two => /^\d+$/,
					},
				},
			],
			steps => [
				{
					part => 'Stash',
					static => {
						stashname => 'basetype',
						method    => 'find_basetype',
					},
				},
			],
		},
	];
#	say STDERR Dumper( JSON->new->encode($data));
	update_engine('basetype', $data);
}

our $schema;

sub update_engine {
	my ($engine, $recipe) = @_;
	$schema->insert_or_update_engine({name => $engine}, {recipe => $recipe});
	say STDERR Dumper $recipe, $schema->find_engine({name => $engine});
}


sub do_it {
	my $configbase = 'etc/';
	my $config = Jet::Config->new(base => $configbase);
	my @connect_info = @{ $config->jet->{connect_info} };
	my %connect_info;
	$connect_info{$_} = shift @connect_info for qw/dbname username password connect_options/;
	$schema = Jet::Stuff->new(%connect_info);
	basetype_engine;
}

do_it;