#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use JSON;

use Data::Dumper;

use Jet::Config;
use Jet::Stuff;

sub basetype_engine {
	my $data = [
		{
			name => 'List',
			conditions => [
				{
					part => 'Jet::Engine::Condition::Compare',
					default => {
						one => {arg => 1},
						two => undef,
					},
				},
			],
			steps => [
				{
					part => 'Jet::Engine::Part::Stash::Stuff',
					default => {
						stashname  => 'basetypes',
						methodname => 'get_basetypes',
						order      => 'id',
					},
				},
			],
		},
		{
			name => 'Create',
			conditions => [
				{
					part => 'Jet::Engine::Condition::Compare',
					default => {
						two => undef,
					},
				},
				{
					part => 'Jet::Engine::Condition::Request::Method',
					default => {
						requestmethod  => ['POST'],
					},
				},
			],
			steps => [
				{
					part => 'Jet::Engine::Part::Update',
					default => {
						stashname  => 'basetype',
						methodname => 'update_basetype',
					},
				},
			],
		},
		{
			name => 'Update',
			conditions => [
				{
					part => 'Jet::Engine::Condition::Compare',
					default => {
						two => qr/^\d+$/,
					},
				},
				{
					part => 'Jet::Engine::Condition::Request::Method',
					default => {
						requestmethod  => ['POST'],
					},
				},
			],
			steps => [
				{
					part => 'Jet::Engine::Part::Update',
					default => {
						stashname  => 'basetype',
						methodname => 'update_basetype',
					},
				},
				{
					part => 'Jet::Engine::Part::Stash::Stuff',
					default => {
						stashname  => 'basetype',
						methodname => 'find_basetype',
					},
				},
			],
		},
		{
			name => 'Retrieve',
			template => 'basetype/jet/config/basetype/display.tx',
			conditions => [
				{
					name => 'arg1',
					part => 'Jet::Engine::Condition::Compare',
					default => {
						one => {arg => 1},
						two => 'id',
					},
				},
				{
					name => 'arg2',
					part => 'Jet::Engine::Condition::Compare',
					default => {
						one => {arg => 2},
						two => qr/^\d+$/,
					},
				},
			],
			steps => [
				{
					part => 'Jet::Engine::Part::Stash::Basetype',
					default => {
						stashname  => 'basetype',
						key => 'id',
						value => {arg => 2},
					},
				},
				{
					part => 'Jet::Engine::Part::Stash',
					default => {
						stashname  => 'fields',
						something => [qw/
							a b c
						/],
					},
				},
			],
		},
	];
#	say STDERR Dumper( JSON->new->encode($data));
	update_engine('basetype', $data);
}

our $schema;

sub update_engine {
	my ($engine, $recipe) = @_;
	$schema->insert_or_update_engine({name => $engine}, {recipe => $recipe});
	my $found = $schema->find_engine({name => $engine});
	say STDERR Dumper $found->{recipe}->recipe;
}


sub do_it {
	my $configbase = 'etc/';
	my $config = Jet::Config->new(base => $configbase);
	my @connect_info = @{ $config->jet->{connect_info} };
	my %connect_info;
	$connect_info{$_} = shift @connect_info for qw/dbname username password connect_options/;
	$schema = Jet::Stuff->new(%connect_info);
	basetype_engine;
}

do_it;