#!/bin/sh
# Create all types, functions, tables and views in the correct order.

# Usage:
#   sql/create_all | psql <database>

# sql/functionality.sql\
FILES="\
 sql/jet.sql\
 sql/basic.sql\
 sql/search.sql\
 sql/import.sql\
"
cat $FILES
