#!/bin/sh
# Create all types, functions, tables and views in the correct order.

# Usage:
#   sql/create_all | psql <database>

# sql/functionality.sql\
FILES="\
 sql/djet.sql\
 sql/basic.sql\
 sql/cart.sql\
 sql/search.sql\
 sql/import.sql\
 sql/news.sql\
 sql/contactform.sql\
 sql/user.sql\
 sql/roles.sql\
"
cat $FILES
